export const RPC = {
    RPC_GET_DECK_BY_IDS: 'RPC_GET_DECK_BY_IDS',
    RPC_UPDATE_DECK_BY_ID: 'RPC_UPDATE_DECK_BY_ID',
    RPC_UPDATE_WORDS_BY_IDS: 'RPC_UPDATE_WORDS_BY_IDS',
    RPC_GET_USER_INFO: 'RPC_GET_USER_INFO',
    RPC_CREATE_DECK: 'RPC_CREATE_DECK',
    RPC_CREATE_WORDS: 'RPC_CREATE_WORDS',
    RPC_UPDATE_USER_INFO: 'RPC_UPDATE_USER_INFO',
    RPC_GET_DECK_BY_INVITE_CODE: 'RPC_GET_DECK_BY_INVITE_CODE',
}