export const RPC = {
    RPC_GET_DECK_BY_IDS: 'RPC_GET_DECK_BY_IDS',
    RPC_UPDATE_WORDS_BY_IDS: 'RPC_UPDATE_WORDS_BY_IDS',
    RPC_GET_USER_INFO: 'RPC_GET_USER_INFO',
    RPC_CREATE_DECK: 'RPC_CREATE_DECK',
}